create table if not exists conversations (
  id bigint generated by default as identity primary key,
  sender_id text not null,
  role text not null check (role in ('user', 'assistant')),
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists leads (
  id bigint generated by default as identity primary key,
  sender_id text not null,
  phone_number text not null,
  service_interest text,
  business_page text,
  goal text,
  preferred_platform text,
  original_message text,
  handoff_requested boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists handoff_users (
  sender_id text primary key,
  active boolean not null default true,
  service_interest text,
  updated_at timestamptz not null default now()
);

create table if not exists processed_messages (
  message_id text primary key,
  sender_id text not null,
  created_at timestamptz not null default now()
);
